---
- name: install git
  yum:
    name: git
    state: latest

- name: put nginx.repo
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
- name: install nginx
  yum:
    name: nginx
    state: latest
- name: write nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: install java
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: daemon sample-spring-boot
  template:
    src: sample-spring-boot.service.j2
    dest: /etc/systemd/system/sample-spring-boot.service
  notify:
    - daemon-reload sample-spring-boot
    - restart sample-spring-boot
