---
- hosts: webserver
  remote_user: vagrant
  become: yes

  vars:
    ansistrano_deploy_to: /var/www/sample-spring-boot
  roles:
    - ansistrano.deploy

  tasks:
    - name: trigger to restart jar
      command: echo ''
      changed_when: true
      notify:
        - restart sample-spring-boot

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
    - name: daemon-reload sample-spring-boot
      systemd:
        name: sample-spring-boot
        daemon-reload: yes
    - name: restart sample-spring-boot
      service:
        name: sample-spring-boot
        state: restarted
        enabled: yes
